export const districts = [
  "Adilabad",
  "Agra",
  "Alappuzha",
  "Aligarh",
  "Alirajpur",
  "Ambala",
  "Amethi",
  "Amreli",
  "Amroha",
  "Anand",
  "Anantnag",
  "Ariyalur",
  "Azamgarh",
  "Badaun",
  "Badgam",
  "Badwani",
  "Bahraich",
  "Balaghat",
  "Balodabazar",
  "Balrampur",
  "Banaskanth",
  "Bankura",
  "Barabanki",
  "Bareilly",
  "Bargarh",
  "Barpeta",
  "Beawar",
  "Belgaum",
  "Bharuch",
  "Bhatinda",
  "Bhavnagar",
  "Bhilwara",
  "Bijnor",
  "Birbhum",
  "Bulandshahar",
  "Buxar",
  "Chamba",
  "Champawat",
  "Chandigarh",
  "Chengalpattu",
  "Chikmagalur",
  "Coimbatore",
  "Cuddalore",
  "Dahod",
  "Darjeeling",
  "Davangere",
  "Dehradoon",
  "Devbhumi Dwarka",
  "Dhamtari",
  "Dhar",
  "Dharmapuri",
  "Dharwad",
  "Dindigul",
  "Dindori",
  "Dudu",
  "East Godavari",
  "Ernakulam",
  "Erode",
  "Etah",
  "Farukhabad",
  "Fatehgarh",
  "Fazilka",
  "Gadchiroli",
  "Gajapati",
  "Gandhinagar",
  "Ganganagar",
  "Gir Somnath",
  "Gonda",
  "Guntur",
  "Gurgaon",
  "Haridwar",
  "Hassan",
  "Hissar",
  "Hoshiarpur",
  "Idukki",
  "Indore",
  "Jalandhar",
  "Jalaun (Orai)",
  "Jammu",
  "Jamnagar",
  "Jhajar",
  "Jhansi",
  "Jind",
  "Jodhpur",
  "Junagarh",
  "Kallakuruchi",
  "Kancheepuram",
  "Kangra",
  "Kannur",
  "Karimnagar",
  "Karur",
  "Karwar(Uttar Kannad)",
  "Kathua",
  "Khammam",
  "Khargone",
  "Khiri (Lakhimpur)",
  "Kollam",
  "Koppal",
  "Kottayam",
  "Kozhikode(Calicut)",
  "Krishnagiri",
  "Kullu",
  "Kurnool",
  "Kurukshetra",
  "Lakhimpur",
  "Ludhiana",
  "Madurai",
  "Maharajganj",
  "Mahbubnagar",
  "Mahendragarh-Narnaul",
  "Mainpuri",
  "Malappuram",
  "Mandi",
  "Mandla",
  "Mansa",
  "Mau(Maunathbhanjan)",
  "Mayurbhanja",
  "Medak",
  "Medinipur(W)",
  "Mehsana",
  "Mirzapur",
  "Mohali",
  "Mokokchung",
  "Morbi",
  "Murshidabad",
  "Nagapattinam",
  "Nagercoil (Kannyiakumari)",
  "Nalbari",
  "Nalgonda",
  "Namakkal",
  "Narmada",
  "Narsinghpur",
  "Nashik",
  "Palakad",
  "Pali",
  "Panchmahals",
  "Panipat",
  "Pathanamthitta",
  "Patiala",
  "Perambalur",
  "Pillibhit",
  "Pudukkottai",
  "Pulwama",
  "Pune",
  "Puruliya",
  "Raebarelli",
  "Raichur",
  "Raigad",
  "Raigarh",
  "Raipur",
  "Raisen",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri",
  "Ramanathapuram",
  "Rampur",
  "Ranipet",
  "Rewari",
  "Ropar (Rupnagar)",
  "Sabarkantha",
  "Salem",
  "Sambhal",
  "Sangrur",
  "Shamli",
  "Siddharth Nagar",
  "Sirsa",
  "Sitapur",
  "Sivaganga",
  "Sonipat",
  "South Goa",
  "Srinagar",
  "Surendranagar",
  "Surguja",
  "Tarntaran",
  "Tenkasi",
  "Thanjavur",
  "The Nilgiris",
  "Theni",
  "Thirssur",
  "Thiruchirappalli",
  "Thirunelveli",
  "Thirupathur",
  "Thirupur",
  "Thiruvananthapuram",
  "Thiruvannamalai",
  "Thiruvarur",
  "Thiruvellore",
  "Tuticorin",
  "UdhamSinghNagar",
  "Valsad",
  "Vellore",
  "Villupuram",
  "Virudhunagar",
  "Warangal",
  "Wayanad",
  "Yamuna Nagar",
];

export const states = [
  "Andhra Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "Uttrakhand",
  "West Bengal",
];

export const markets = [
  "AJattihalli(Uzhavar Sandhai )",
  "Adilabad",
  "Adimali",
  "Agra",
  "Ahmedgarh",
  "Alampur",
  "Alangudi(Uzhavar Sandhai )",
  "Aliganj",
  "Aligarh",
  "Alirajpur",
  "Amalapuram  VFPCK",
  "Ambasamudram(Uzhavar Sandhai )",
  "Ambattur(Uzhavar Sandhai )",
  "Ambikapur",
  "Ammapet(Uzhavar Sandhai )",
  "Ammoor",
  "Anaiyur(Uzhavar Sandhai )",
  "Anandnagar",
  "Anchal",
  "Andipatti(Uzhavar Sandhai )",
  "Anjad",
  "Anna nagar(Uzhavar Sandhai )",
  "Arani(Uzhavar Sandhai )",
  "Aranthangi(Uzhavar Sandhai )",
  "Arasikere",
  "Arcot(Uzhavar Sandhai )",
  "Ariyalur(Uzhavar Sandhai)",
  "Armori",
  "Aruppukottai(Uzhavar Sandhai )",
  "Ashahipora (Anantnagh)",
  "Athirampuzha",
  "Athur(Uzhavar Sandhai )",
  "Attabira",
  "Attayampatti(Uzhavar Sandhai )",
  "Avallapalli(Uzhavar Sandhai )",
  "Azamgarh",
  "Bachranwa",
  "Badayoun",
  "Badwaha",
  "Bagasara",
  "Bahadurgarh",
  "Balarampur",
  "Barabanki",
  "Bareilly",
  "Bareli",
  "Barpeta Road",
  "Bassi Pathana",
  "Batote",
  "Bazpur",
  "Belarbahara",
  "Belargaon",
  "Bhadrachalam",
  "Bhagta Bhai Ka",
  "Bhavnagar",
  "Bhesan",
  "Bhongir",
  "Bhuntar",
  "Bichhiya",
  "Birbhum",
  "Bodinayakanur(Uzhavar Sandhai )",
  "Boraee",
  "Brahmpur",
  "Budalada",
  "Buland Shahr",
  "Chamba",
  "Chamkaur Sahib",
  "Chandigarh(Grain/Fruit)",
  "Charla",
  "Charra",
  "Chavakkad",
  "Chengalpet(Uzhavar Sandhai )",
  "Chengam(Uzhavar Sandhai )",
  "Chengannur",
  "Cheyyar(Uzhavar Sandhai )",
  "Chhachrauli",
  "Chhuria",
  "Chidambaram(Uzhavar Sandhai )",
  "Chikkamagalore",
  "Chinnalapatti(Uzhavar Sandhai )",
  "Chinnamanur(Uzhavar Sandhai )",
  "Chokkikulam(Uzhavar Sandhai )",
  "Coonoor(Uzhavar Sandhai )",
  "Cuddalore(Uzhavar Sandhai )",
  "Curchorem",
  "Dahod",
  "Deesa(Deesa Veg Yard)",
  "Dehgam",
  "Dehgam(Rekhiyal)",
  "Denkanikottai(Uzhavar Sandhai )",
  "Devakottai (Uzhavar Sandhai )",
  "Devarakonda",
  "Devaram(Uzhavar Sandhai )",
  "Devarkonda(Dindi)",
  "Devarkonda(Mallepalli)",
  "Devgadhbaria",
  "Dhamnod",
  "Dhanaura",
  "Dharapuram(Uzhavar Sandhai )",
  "Dharmapuri(Uzhavar Sandhai )",
  "Dhoraji",
  "Dhragradhra",
  "Dhrol",
  "Dindigul(Uzhavar Sandhai )",
  "Dindori",
  "Divai",
  "Dongargaon",
  "Dubbak",
  "Dudu",
  "Edapadi (Uzhavar Sandhai )",
  "Elampillai(Uzhavar Sandhai )",
  "Etah",
  "Ettumanoor",
  "Farukhabad",
  "Fazilka",
  "Gadarpur",
  "Gadarwada",
  "Gadwal(Lezza)",
  "Gajwel",
  "Ganaur",
  "Gandarvakottai(Uzhavar Sandhai )",
  "Garh Shankar",
  "GarhShankar (Kotfatuhi)",
  "Gattasilli",
  "Ghatal",
  "Ghiraur",
  "Gingee(Uzhavar Sandhai )",
  "Gobichettipalayam(Uzhavar Sandhai )",
  "Gogamba",
  "Gogamba(Similiya)",
  "Gohana",
  "Gonda",
  "Gondal(Veg.market Gondal)",
  "Gudalur(Uzhavar Sandhai )",
  "Gudiyatham(Uzhavar Sandhai )",
  "Guduvancheri(Uzhavar Sandhai )",
  "Gulabpura",
  "Gurgaon",
  "Haliyala",
  "Halvad",
  "Hansi",
  "Harappana Halli",
  "Hargaon (Laharpur)",
  "Haridwar Union",
  "Harippad",
  "Harur(Uzhavar Sandhai )",
  "Hasthampatti(Uzhavar Sandhai )",
  "Hosur(Uzhavar Sandhai )",
  "Husnabad",
  "Huzzurabad",
  "Indore",
  "Irinjalakkuda",
  "Jalagandapuram(Uzhavar Sandhai )",
  "Jalalabad",
  "Jalandhar City",
  "Jalandhar City(Jalandhar)",
  "Jalandhar City(Kartar Pur Dana mandi)",
  "Jalaun",
  "Jam Khambalia",
  "Jambusar",
  "Jambusar(Kaavi)",
  "Jameenrayapettai(Uzhavar Sandhai )",
  "Jangipur",
  "Jasdan",
  "Jetpur(Dist.Rajkot)",
  "Jeyankondam (Uzhavar Sandhai )",
  "Jhansi",
  "Jodhpur (F&V)",
  "Junagadh",
  "Kadakkal  VFPCK",
  "Kahithapattarai(Uzhavar Sandhai )",
  "Kairana",
  "Kalagategi",
  "Kalanjoor  VFPCK",
  "Kalavai",
  "Kalawad",
  "Kallachi",
  "Kallakurichi(Uzhavar Sandhai )",
  "Kalol",
  "Kambam(Uzhavar Sandhai )",
  "Kamlaganj",
  "Kancheepuram(Uzhavar Sandhai )",
  "Kandi",
  "Kandiyaperi(Uzhavar Sandhai )",
  "Kangayam(Uzhavar Sandhai )",
  "Kangra",
  "Kangra(Baijnath)",
  "Kangra(Jaisinghpur)",
  "Kangra(Nagrota Bagwan)",
  "Kanjirappally",
  "Karaikudi",
  "Karaikudi(Uzhavar Sandhai )",
  "Karambakkudi(Uzhavar Sandhai )",
  "Karanjia",
  "Karapa",
  "Kariyapatti(Uzhavar Sandhai )",
  "Karjat(Raigad)",
  "Karur(Uzhavar Sandhai )",
  "Kasdol",
  "Kasrawad",
  "Kathua",
  "Katpadi (Uzhavar Sandhai )",
  "Kaveripattinam(Uzhavar Sandhai )",
  "Kayamganj",
  "Keelpennathur(Uzhavar Sandhai )",
  "Khair",
  "Khambhat(Veg Yard Khambhat)",
  "Khanna",
  "Kharar",
  "Khargone",
  "Khateema",
  "Khatra",
  "Khetia",
  "Kicchha",
  "Kiratpur",
  "Koduvayoor",
  "Kollam",
  "Kollayil  VFPCK",
  "Kollengode",
  "Kondotty",
  "Koovapadi VFPCK",
  "Kopaganj",
  "Kosli",
  "Kottakkal",
  "Kottayam",
  "Kovilpatti(Uzhavar Sandhai )",
  "Krishnagiri(Uzhavar Sandhai )",
  "Kukshi",
  "Kulgam",
  "Kulithalai(Uzhavar Sandhai )",
  "Kullu",
  "Kullu(Chauri Bihal)",
  "Kullu(Patli Kuhal)",
  "Kumarapalayam(Uzhavar Sandhai )",
  "Kumbakonam (Uzhavar Sandhai )",
  "Kundrathur(Uzhavar Sandhai )",
  "Kurichi(Uzhavar Sandhai )",
  "Kuruppanthura",
  "Kustagi",
  "Ladwa",
  "Lakhimpur",
  "Lakshar",
  "Lalganj",
  "Lalgudi(Uzhavar Sandhai )",
  "Lingasugur",
  "Madathukulam",
  "Madhira",
  "Madhuranthagam(Uzhavar Sandhai )",
  "Maigalganj",
  "Mainpuri",
  "Mallial(Cheppial)",
  "Manachanallur(Uzhavar Sandhai )",
  "Manakodur",
  "Manapparai(Uzhavar Sandhai )",
  "Manawar",
  "Mandi(Mandi)",
  "Mandi(Takoli)",
  "Mandla",
  "Manglaur",
  "Mannargudi I(Uzhavar Sandhai )",
  "Mannargudi II(Uzhavar Sandhai )",
  "Maranelloor VFPCK",
  "Mayiladuthurai(Uzhavar Sandhai )",
  "Medavakkam(Uzhavar Sandhai )",
  "Melapalayam(Uzhavar Sandhai )",
  "Melur(Uzhavar Sandhai )",
  "Mettupalayam(Uzhavar Sandhai )",
  "Mettur(Uzhavar Sandhai )",
  "Mezhuveli  VFPCK",
  "Miryalaguda",
  "Mirzapur",
  "Modasa",
  "Modasa(Tintoi)",
  "Mohanur(Uzhavar Sandhai )",
  "Mohgaon",
  "Moothedam  VFPCK",
  "Morinda",
  "Morva Hafad",
  "Mukerian(Talwara)",
  "Mukkom",
  "Mullana",
  "Muriyad  VFPCK",
  "Musiri(Uzhavar Sandhai )",
  "Muthupettai(Uzhavar Sandhai )",
  "Myladi(Uzhavar Sandhai )",
  "NGO Colony(Uzhavar Sandhai )",
  "Naanpara",
  "Nagapattinam(Uzhavar Sandhai )",
  "Nagari",
  "Nalbari",
  "Namakkal(Uzhavar Sandhai )",
  "Nandyal",
  "Naravarikuppam(Uzhavar Sandhai )",
  "Narnaul",
  "Narwal Jammu (F&V)",
  "Narwana",
  "Natrampalli(Uzhavar Sandhai )",
  "Nautnava",
  "Needamangalam(Uzhavar Sandhai )",
  "Nelakondapally",
  "Neredcherla",
  "North Paravur",
  "Padappai(Uzhavar Sandhai )",
  "Pala",
  "Palacode(Uzhavar Sandhai )",
  "Palampur",
  "Palanganatham(Uzhavar Sandhai )",
  "Palani",
  "Palani(Uzhavar Sandhai )",
  "Palayamkottai(Uzhavar Sandhai )",
  "Palladam(Uzhavar Sandhai )",
  "Pallapatti (Uzhavar Sandhai )",
  "Pallavaram(Uzhavar Sandhai )",
  "Pampady",
  "Panchpedwa",
  "Panipat",
  "Panruti(Uzhavar Sandhai )",
  "Papanasam(Uzhavar Sandhai )",
  "Paramakudi(Uzhavar Sandhai )",
  "Paramathivelur(Uzhavar Sandhai )",
  "Parassala",
  "Parimpore",
  "Parlakhemundi",
  "Paruthipattu(Uzhavar Sandhai )",
  "Patiala",
  "Pattambi",
  "Patti",
  "Pattukottai(Uzhavar Sandhai )",
  "Peddapalli",
  "Pennagaram(Uzhavar Sandhai )",
  "Perambalur(Uzhavar Sandhai )",
  "Periyakulam(Uzhavar Sandhai )",
  "Periyar Nagar(Uzhavar Sandhai )",
  "Perumbavoor",
  "Perundurai(Uzhavar Sandhai )",
  "Pimpalgaon",
  "Pollachi(Uzhavar Sandhai )",
  "Polur(Uzhavar Sandhai )",
  "Pramadom VFPCK",
  "Pudukottai(Uzhavar Sandhai )",
  "Pudur",
  "Pulwama (F&V)",
  "Pune",
  "Pune(Moshi)",
  "RSPuram(Uzhavar Sandhai )",
  "Raibareilly",
  "Raipur",
  "Rajapalayam(Uzhavar Sandhai )",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri (F&V)",
  "Rajpipla",
  "Ramanathapuram(Uzhavar Sandhai )",
  "Ramannapet",
  "Rampuraphul(Nabha Mandi)",
  "Rampurhat",
  "Rani",
  "Rania",
  "Ranipettai(Uzhavar Sandhai )",
  "Rasipuram(Uzhavar Sandhai )",
  "Ravulapelem",
  "Rewari",
  "Rishikesh",
  "Roorkee",
  "Safdarganj",
  "Sahiyapur",
  "Salon",
  "Sambhal",
  "Sampath Nagar(Uzhavar Sandhai )",
  "Sanawad",
  "Sankarankoil(Uzhavar Sandhai )",
  "Sankarapuram(Uzhavar Sandhai )",
  "Sankeshwar",
  "Sarangarh",
  "Sathiyamagalam(Uzhavar Sandhai )",
  "Sathur(Uzhavar Sandhai )",
  "Sattupalli",
  "Savarkundla",
  "Sendhwa",
  "Shahaswan",
  "Shamli",
  "Shopian",
  "Siddipet",
  "Sikanderabad",
  "Siliguri",
  "Singampunari(Uzhavar Sandhai )",
  "Singanallur(Uzhavar Sandhai )",
  "Sirkali(Uzhavar Sandhai )",
  "Sitapur",
  "Sivagangai (Uzhavar Sandhai )",
  "Sivakasi(Uzhavar Sandhai )",
  "Siyana",
  "Sooramangalam(Uzhavar Sandhai )",
  "Sriganganagar (F&V)",
  "Srivilliputhur(Uzhavar Sandhai )",
  "Sultanpur",
  "Sulur(Uzhavar Sandhai )",
  "Sundarapuram(Uzhavar Sandhai )",
  "Suratgarh",
  "Taliparamba",
  "Talwandi Sabo",
  "Tamarainagar(Uzhavar Sandhai )",
  "Tanakpur",
  "Tenali",
  "Tenkasi(Uzhavar Sandhai )",
  "Thalasserry",
  "Thalavadi(Uzhavar Sandhai )",
  "Thalavaipuram(Uzhavar Sandhai )",
  "Thalayolaparambu",
  "Thammampatti (Uzhavar Sandhai )",
  "Thanjavur(Uzhavar Sandhai )",
  "Thathakapatti(Uzhavar Sandhai )",
  "Theni(Uzhavar Sandhai )",
  "Thirukalukundram(Uzhavar Sandhai )",
  "Thirumangalam(Uzhavar Sandhai )",
  "Thirupathur",
  "Thondernad  VFPCK",
  "Thoothukudi",
  "Thrippunithura",
  "Thuraiyur",
  "Tindivanam",
  "Tiruchengode",
  "Tirupatthur(Uzhavar Sandhai )",
  "Tiruppur (North) (Uzhavar Sandhai )",
  "Tiruppur (South) (Uzhavar Sandhai )",
  "Tiruthuraipoondi(Uzhavar Sandhai )",
  "Tiruttani",
  "Tiruvallur(Uzhavar Sandhai )",
  "Tiruvannamalai(Uzhavar Sandhai )",
  "Tiruvarur(Uzhavar Sandhai )",
  "Tiruvellore",
  "Tuli",
  "Tuticorin(Uzhavar Sandhai )",
  "Udhagamandalam(Uzhavar Sandhai )",
  "Udumalpet",
  "Uklana",
  "Ulundurpettai",
  "Unava",
  "Usilampatty",
  "Uthiramerur",
  "Vadakkenchery",
  "Vadaseri",
  "Vadavalli(Uzhavar Sandhai )",
  "Valangaiman",
  "Valsad",
  "Vandavasi",
  "Vaniyamkulam  VFPCK",
  "Vaniyampadi(Uzhavar Sandhai )",
  "Vedasanthur(Uzhavar Sandhai )",
  "Velayuthampalayam(Uzhavar Sandhai )",
  "Vellore",
  "Vemulawada",
  "Veraval",
  "Vijaynagar",
  "Vikasnagar",
  "Vilaspur",
  "Viralimalai(Uzhavar Sandhai )",
  "Virudhunagar(Uzhavar Sandhai )",
  "Viruthachalam(Uzhavar Sandhai )",
  "Visavadar",
  "Vishalpur",
  "Viswan",
  "Voligonda",
  "Warangal",
  "Wazirganj",
  "Wyra",
  "Yalburga",
  "Zaloosa-Chararishrief (F&V)",
  "kalanwali",
];

export const grades = ["FAQ", "Large", "Local", "Medium", "Small"];

export const varieties = [
  "1001",
  "777 New Ind",
  "ADT 37",
  "American",
  "Amruthapani",
  "Ankola",
  "Annabesahai",
  "Apple",
  "Arhar (Whole)",
  "Arhar Dal(Tur)",
  "B P T",
  "Banana - Ripe",
  "Besrai",
  "Bhushavali(Pacha)",
  "Big",
  "Black",
  "Black Gram (Whole)",
  "Chakkarakeli(Red)",
  "Chakkarakeli(White)",
  "Coconut",
  "Common",
  "Cotton (Unginned)",
  "Darjeeling",
  "Delicious",
  "Deshi Red",
  "Deshi White",
  "Desi",
  "Desi(Bontha)",
  "Dhan",
  "Dollar Gram",
  "Dusheri",
  "French",
  "Green (Whole)",
  "Green Gram Dhall-I",
  "H-4(A) 27mm FIne",
  "Hybrid",
  "Hybrid Red (Cattle Feed)",
  "Hybrid/Local",
  "I.R. 36",
  "I.R. 64",
  "I.R.-64",
  "Karbhuja",
  "Karpura",
  "Kasmir/Shimla - II",
  "Kullu Royal Delicious",
  "Local",
  "Local (Whole)",
  "MTU-1010",
  "Masoor Gola",
  "Masur Dal",
  "Medium",
  "Nagpuri",
  "Narma BT Cotton",
  "Nendra Bale",
  "Orange",
  "Other",
  "Paddy",
  "Paddy Coarse",
  "Paddy Medium",
  "Paddy fine",
  "Paddy-Organic",
  "Palayamthodan",
  "Papaya",
  "Pomogranate",
  "Poovan",
  "RCH-2",
  "Rasakathai",
  "Red  Gold",
  "Red Banana",
  "Robusta",
  "Royal Delicious",
  "Safeda",
  "Samba Masuri",
  "Sarvati",
  "Shanker 6 (B) 30mm FIne",
  "Simla",
  "Small",
  "Sona",
  "Sona Mahsuri",
  "Swarna Masuri (New)",
  "TD-5",
  "Tur/Arhar-Organic",
  "Urda/Urd",
  "Water Melon",
  "White (SAFED)",
  "Without Ginned Cotton",
  "Yellow",
];