export const states = [  
      {  
         "state":"Andhra Pradesh",
         "districts":[  
            "Anantapur",
            "Chittoor",
            "East Godavari",
            "Guntur",
            "Krishna",
            "Kurnool",
            "Nellore",
            "Prakasam",
            "Srikakulam",
            "Visakhapatnam",
            "Vizianagaram",
            "West Godavari",
            "YSR Kadapa"
         ]
      },
      {  
         "state":"Arunachal Pradesh",
         "districts":[  
            "Tawang",
            "West Kameng",
            "East Kameng",
            "Papum Pare",
            "Kurung Kumey",
            "Kra Daadi",
            "Lower Subansiri",
            "Upper Subansiri",
            "West Siang",
            "East Siang",
            "Siang",
            "Upper Siang",
            "Lower Siang",
            "Lower Dibang Valley",
            "Dibang Valley",
            "Anjaw",
            "Lohit",
            "Namsai",
            "Changlang",
            "Tirap",
            "Longding"
         ]
      },
      {  
         "state":"Assam",
         "districts":[  
            "Baksa",
            "Barpeta",
            "Biswanath",
            "Bongaigaon",
            "Cachar",
            "Charaideo",
            "Chirang",
            "Darrang",
            "Dhemaji",
            "Dhubri",
            "Dibrugarh",
            "Goalpara",
            "Golaghat",
            "Hailakandi",
            "Hojai",
            "Jorhat",
            "Kamrup Metropolitan",
            "Kamrup",
            "Karbi Anglong",
            "Karimganj",
            "Kokrajhar",
            "Lakhimpur",
            "Majuli",
            "Morigaon",
            "Nagaon",
            "Nalbari",
            "Dima Hasao",
            "Sivasagar",
            "Sonitpur",
            "South Salmara-Mankachar",
            "Tinsukia",
            "Udalguri",
            "West Karbi Anglong"
         ]
      },
      {  
         "state":"Bihar",
         "districts":[  
            "Araria",
            "Arwal",
            "Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "Darbhanga",
            "East Champaran (Motihari)",
            "Gaya",
            "Gopalganj",
            "Jamui",
            "Jehanabad",
            "Kaimur (Bhabua)",
            "Katihar",
            "Khagaria",
            "Kishanganj",
            "Lakhisarai",
            "Madhepura",
            "Madhubani",
            "Munger (Monghyr)",
            "Muzaffarpur",
            "Nalanda",
            "Nawada",
            "Patna",
            "Purnia (Purnea)",
            "Rohtas",
            "Saharsa",
            "Samastipur",
            "Saran",
            "Sheikhpura",
            "Sheohar",
            "Sitamarhi",
            "Siwan",
            "Supaul",
            "Vaishali",
            "West Champaran"
         ]
      },
      {  
         "state":"Chandigarh (UT)",
         "districts":[  
            "Chandigarh"
         ]
      },
      {  
         "state":"Chhattisgarh",
         "districts":[  
            "Balod",
            "Baloda Bazar",
            "Balrampur",
            "Bastar",
            "Bemetara",
            "Bijapur",
            "Bilaspur",
            "Dantewada (South Bastar)",
            "Dhamtari",
            "Durg",
            "Gariyaband",
            "Janjgir-Champa",
            "Jashpur",
            "Kabirdham (Kawardha)",
            "Kanker (North Bastar)",
            "Kondagaon",
            "Korba",
            "Korea (Koriya)",
            "Mahasamund",
            "Mungeli",
            "Narayanpur",
            "Raigarh",
            "Raipur",
            "Rajnandgaon",
            "Sukma",
            "Surajpur  ",
            "Surguja"
         ]
      },
      {  
         "state":"Dadra and Nagar Haveli (UT)",
         "districts":[  
            "Dadra & Nagar Haveli"
         ]
      },
      {  
         "state":"Daman and Diu (UT)",
         "districts":[  
            "Daman",
            "Diu"
         ]
      },
      {  
         "state":"Delhi (NCT)",
         "districts":[  
            "Central Delhi",
            "East Delhi",
            "New Delhi",
            "North Delhi",
            "North East  Delhi",
            "North West  Delhi",
            "Shahdara",
            "South Delhi",
            "South East Delhi",
            "South West  Delhi",
            "West Delhi"
         ]
      },
      {  
         "state":"Goa",
         "districts":[  
            "North Goa",
            "South Goa"
         ]
      },
      {  
         "state":"Gujarat",
         "districts":[  
            "Ahmedabad",
            "Amreli",
            "Anand",
            "Aravalli",
            "Banaskantha (Palanpur)",
            "Bharuch",
            "Bhavnagar",
            "Botad",
            "Chhota Udepur",
            "Dahod",
            "Dangs (Ahwa)",
            "Devbhoomi Dwarka",
            "Gandhinagar",
            "Gir Somnath",
            "Jamnagar",
            "Junagadh",
            "Kachchh",
            "Kheda (Nadiad)",
            "Mahisagar",
            "Mehsana",
            "Morbi",
            "Narmada (Rajpipla)",
            "Navsari",
            "Panchmahal (Godhra)",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Sabarkantha (Himmatnagar)",
            "Surat",
            "Surendranagar",
            "Tapi (Vyara)",
            "Vadodara",
            "Valsad"
         ]
      },
      {  
         "state":"Haryana",
         "districts":[  
            "Ambala",
            "Bhiwani",
            "Charkhi Dadri",
            "Faridabad",
            "Fatehabad",
            "Gurgaon",
            "Hisar",
            "Jhajjar",
            "Jind",
            "Kaithal",
            "Karnal",
            "Kurukshetra",
            "Mahendragarh",
            "Mewat",
            "Palwal",
            "Panchkula",
            "Panipat",
            "Rewari",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Yamunanagar"
         ]
      },
      {  
         "state":"Himachal Pradesh",
         "districts":[  
            "Bilaspur",
            "Chamba",
            "Hamirpur",
            "Kangra",
            "Kinnaur",
            "Kullu",
            "Lahaul &amp; Spiti",
            "Mandi",
            "Shimla",
            "Sirmaur (Sirmour)",
            "Solan",
            "Una"
         ]
      },
      {  
         "state":"Jammu and Kashmir",
         "districts":[  
            "Anantnag",
            "Bandipore",
            "Baramulla",
            "Budgam",
            "Doda",
            "Ganderbal",
            "Jammu",
            "Kargil",
            "Kathua",
            "Kishtwar",
            "Kulgam",
            "Kupwara",
            "Leh",
            "Poonch",
            "Pulwama",
            "Rajouri",
            "Ramban",
            "Reasi",
            "Samba",
            "Shopian",
            "Srinagar",
            "Udhampur"
         ]
      },
      {  
         "state":"Jharkhand",
         "districts":[  
            "Bokaro",
            "Chatra",
            "Deoghar",
            "Dhanbad",
            "Dumka",
            "East Singhbhum",
            "Garhwa",
            "Giridih",
            "Godda",
            "Gumla",
            "Hazaribag",
            "Jamtara",
            "Khunti",
            "Koderma",
            "Latehar",
            "Lohardaga",
            "Pakur",
            "Palamu",
            "Ramgarh",
            "Ranchi",
            "Sahibganj",
            "Seraikela-Kharsawan",
            "Simdega",
            "West Singhbhum"
         ]
      },
      {  
         "state":"Karnataka",
         "districts":[  
            "Bagalkot",
            "Ballari (Bellary)",
            "Belagavi (Belgaum)",
            "Bengaluru (Bangalore) Rural",
            "Bengaluru (Bangalore) Urban",
            "Bidar",
            "Chamarajanagar",
            "Chikballapur",
            "Chikkamagaluru (Chikmagalur)",
            "Chitradurga",
            "Dakshina Kannada",
            "Davangere",
            "Dharwad",
            "Gadag",
            "Hassan",
            "Haveri",
            "Kalaburagi (Gulbarga)",
            "Kodagu",
            "Kolar",
            "Koppal",
            "Mandya",
            "Mysuru (Mysore)",
            "Raichur",
            "Ramanagara",
            "Shivamogga (Shimoga)",
            "Tumakuru (Tumkur)",
            "Udupi",
            "Uttara Kannada (Karwar)",
            "Vijayapura (Bijapur)",
            "Yadgir"
         ]
      },
      {  
         "state":"Kerala",
         "districts":[  
            "Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kannur",
            "Kasaragod",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thiruvananthapuram",
            "Thrissur",
            "Wayanad"
         ]
      },
      {  
         "state":"Lakshadweep (UT)",
         "districts":[  
            "Agatti",
            "Amini",
            "Androth",
            "Bithra",
            "Chethlath",
            "Kavaratti",
            "Kadmath",
            "Kalpeni",
            "Kilthan",
            "Minicoy"
         ]
      },
      {  
         "state":"Madhya Pradesh",
         "districts":[  
            "Agar Malwa",
            "Alirajpur",
            "Anuppur",
            "Ashoknagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dindori",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa",
            "Khargone",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panna",
            "Raisen",
            "Rajgarh",
            "Ratlam",
            "Rewa",
            "Sagar",
            "Satna",
            "Sehore",
            "Seoni",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha"
         ]
      },
      {  
         "state":"Maharashtra",
         "districts":[  
            "Ahmednagar",
            "Akola",
            "Amravati",
            "Aurangabad",
            "Beed",
            "Bhandara",
            "Buldhana",
            "Chandrapur",
            "Dhule",
            "Gadchiroli",
            "Gondia",
            "Hingoli",
            "Jalgaon",
            "Jalna",
            "Kolhapur",
            "Latur",
            "Mumbai City",
            "Mumbai Suburban",
            "Nagpur",
            "Nanded",
            "Nandurbar",
            "Nashik",
            "Osmanabad",
            "Palghar",
            "Parbhani",
            "Pune",
            "Raigad",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sindhudurg",
            "Solapur",
            "Thane",
            "Wardha",
            "Washim",
            "Yavatmal"
         ]
      },
      {  
         "state":"Manipur",
         "districts":[  
            "Bishnupur",
            "Chandel",
            "Churachandpur",
            "Imphal East",
            "Imphal West",
            "Jiribam",
            "Kakching",
            "Kamjong",
            "Kangpokpi",
            "Noney",
            "Pherzawl",
            "Senapati",
            "Tamenglong",
            "Tengnoupal",
            "Thoubal",
            "Ukhrul"
         ]
      },
      {  
         "state":"Meghalaya",
         "districts":[  
            "East Garo Hills",
            "East Jaintia Hills",
            "East Khasi Hills",
            "North Garo Hills",
            "Ri Bhoi",
            "South Garo Hills",
            "South West Garo Hills ",
            "South West Khasi Hills",
            "West Garo Hills",
            "West Jaintia Hills",
            "West Khasi Hills"
         ]
      },
      {  
         "state":"Mizoram",
         "districts":[  
            "Aizawl",
            "Champhai",
            "Kolasib",
            "Lawngtlai",
            "Lunglei",
            "Mamit",
            "Saiha",
            "Serchhip"
         ]
      },
      {  
         "state":"Nagaland",
         "districts":[  
            "Dimapur",
            "Kiphire",
            "Kohima",
            "Longleng",
            "Mokokchung",
            "Mon",
            "Peren",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto"
         ]
      },
      {  
         "state":"Odisha",
         "districts":[  
            "Angul",
            "Balangir",
            "Balasore",
            "Bargarh",
            "Bhadrak",
            "Boudh",
            "Cuttack",
            "Deogarh",
            "Dhenkanal",
            "Gajapati",
            "Ganjam",
            "Jagatsinghapur",
            "Jajpur",
            "Jharsuguda",
            "Kalahandi",
            "Kandhamal",
            "Kendrapara",
            "Kendujhar (Keonjhar)",
            "Khordha",
            "Koraput",
            "Malkangiri",
            "Mayurbhanj",
            "Nabarangpur",
            "Nayagarh",
            "Nuapada",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Sonepur",
            "Sundargarh"
         ]
      },
      {  
         "state":"Puducherry (UT)",
         "districts":[  
            "Karaikal",
            "Mahe",
            "Pondicherry",
            "Yanam"
         ]
      },
      {  
         "state":"Punjab",
         "districts":[  
            "Amritsar",
            "Barnala",
            "Bathinda",
            "Faridkot",
            "Fatehgarh Sahib",
            "Fazilka",
            "Ferozepur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Muktsar",
            "Nawanshahr (Shahid Bhagat Singh Nagar)",
            "Pathankot",
            "Patiala",
            "Rupnagar",
            "Sahibzada Ajit Singh Nagar (Mohali)",
            "Sangrur",
            "Tarn Taran"
         ]
      },
      {  
         "state":"Rajasthan",
         "districts":[  
            "Ajmer",
            "Alwar",
            "Banswara",
            "Baran",
            "Barmer",
            "Bharatpur",
            "Bhilwara",
            "Bikaner",
            "Bundi",
            "Chittorgarh",
            "Churu",
            "Dausa",
            "Dholpur",
            "Dungarpur",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jalore",
            "Jhalawar",
            "Jhunjhunu",
            "Jodhpur",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Pratapgarh",
            "Rajsamand",
            "Sawai Madhopur",
            "Sikar",
            "Sirohi",
            "Sri Ganganagar",
            "Tonk",
            "Udaipur"
         ]
      },
      {  
         "state":"Sikkim",
         "districts":[  
            "East Sikkim",
            "North Sikkim",
            "South Sikkim",
            "West Sikkim"
         ]
      },
      {  
         "state":"Tamil Nadu",
         "districts":[  
            "Ariyalur",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kanchipuram",
            "Kanyakumari",
            "Karur",
            "Krishnagiri",
            "Madurai",
            "Nagapattinam",
            "Namakkal",
            "Nilgiris",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Salem",
            "Sivaganga",
            "Thanjavur",
            "Theni",
            "Thoothukudi (Tuticorin)",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tiruppur",
            "Tiruvallur",
            "Tiruvannamalai",
            "Tiruvarur",
            "Vellore",
            "Viluppuram",
            "Virudhunagar"
         ]
      },
      {  
         "state":"Telangana",
         "districts":[  
            "Adilabad",
            "Bhadradri Kothagudem",
            "Hyderabad",
            "Jagtial",
            "Jangaon",
            "Jayashankar Bhoopalpally",
            "Jogulamba Gadwal",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Komaram Bheem Asifabad",
            "Mahabubabad",
            "Mahabubnagar",
            "Mancherial",
            "Medak",
            "Medchal",
            "Nagarkurnool",
            "Nalgonda",
            "Nirmal",
            "Nizamabad",
            "Peddapalli",
            "Rajanna Sircilla",
            "Rangareddy",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Wanaparthy",
            "Warangal (Rural)",
            "Warangal (Urban)",
            "Yadadri Bhuvanagiri"
         ]
      },
      {  
         "state":"Tripura",
         "districts":[  
            "Dhalai",
            "Gomati",
            "Khowai",
            "North Tripura",
            "Sepahijala",
            "South Tripura",
            "Unakoti",
            "West Tripura"
         ]
      },
      {  
         "state":"Uttarakhand",
         "districts":[  
            "Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi"
         ]
      },
      {  
         "state":"Uttar Pradesh",
         "districts":[  
            "Agra",
            "Aligarh",
            "Allahabad",
            "Ambedkar Nagar",
            "Amethi (Chatrapati Sahuji Mahraj Nagar)",
            "Amroha (J.P. Nagar)",
            "Auraiya",
            "Azamgarh",
            "Baghpat",
            "Bahraich",
            "Ballia",
            "Balrampur",
            "Banda",
            "Barabanki",
            "Bareilly",
            "Basti",
            "Bhadohi",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Chandauli",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Etawah",
            "Faizabad",
            "Farrukhabad",
            "Fatehpur",
            "Firozabad",
            "Gautam Buddha Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Gorakhpur",
            "Hamirpur",
            "Hapur (Panchsheel Nagar)",
            "Hardoi",
            "Hathras",
            "Jalaun",
            "Jaunpur",
            "Jhansi",
            "Kannauj",
            "Kanpur Dehat",
            "Kanpur Nagar",
            "Kanshiram Nagar (Kasganj)",
            "Kaushambi",
            "Kushinagar (Padrauna)",
            "Lakhimpur - Kheri",
            "Lalitpur",
            "Lucknow",
            "Maharajganj",
            "Mahoba",
            "Mainpuri",
            "Mathura",
            "Mau",
            "Meerut",
            "Mirzapur",
            "Moradabad",
            "Muzaffarnagar",
            "Pilibhit",
            "Pratapgarh",
            "RaeBareli",
            "Rampur",
            "Saharanpur",
            "Sambhal (Bhim Nagar)",
            "Sant Kabir Nagar",
            "Shahjahanpur",
            "Shamali (Prabuddh Nagar)",
            "Shravasti",
            "Siddharth Nagar",
            "Sitapur",
            "Sonbhadra",
            "Sultanpur",
            "Unnao",
            "Varanasi"
         ]
      },
      {  
         "state":"West Bengal",
         "districts":[  
            "Alipurduar",
            "Bankura",
            "Birbhum",
            "Burdwan (Bardhaman)",
            "Cooch Behar",
            "Dakshin Dinajpur (South Dinajpur)",
            "Darjeeling",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Kalimpong",
            "Kolkata",
            "Malda",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "Paschim Medinipur (West Medinipur)",
            "Purba Medinipur (East Medinipur)",
            "Purulia",
            "South 24 Parganas",
            "Uttar Dinajpur (North Dinajpur)"
         ]
      }
   ]

export const markets = [
  "AJattihalli(Uzhavar Sandhai )",
  "Adilabad",
  "Adimali",
  "Agra",
  "Ahmedgarh",
  "Alampur",
  "Alangudi(Uzhavar Sandhai )",
  "Aliganj",
  "Aligarh",
  "Alirajpur",
  "Amalapuram  VFPCK",
  "Ambasamudram(Uzhavar Sandhai )",
  "Ambattur(Uzhavar Sandhai )",
  "Ambikapur",
  "Ammapet(Uzhavar Sandhai )",
  "Ammoor",
  "Anaiyur(Uzhavar Sandhai )",
  "Anandnagar",
  "Anchal",
  "Andipatti(Uzhavar Sandhai )",
  "Anjad",
  "Anna nagar(Uzhavar Sandhai )",
  "Arani(Uzhavar Sandhai )",
  "Aranthangi(Uzhavar Sandhai )",
  "Arasikere",
  "Arcot(Uzhavar Sandhai )",
  "Ariyalur(Uzhavar Sandhai)",
  "Armori",
  "Aruppukottai(Uzhavar Sandhai )",
  "Ashahipora (Anantnagh)",
  "Athirampuzha",
  "Athur(Uzhavar Sandhai )",
  "Attabira",
  "Attayampatti(Uzhavar Sandhai )",
  "Avallapalli(Uzhavar Sandhai )",
  "Azamgarh",
  "Bachranwa",
  "Badayoun",
  "Badwaha",
  "Bagasara",
  "Bahadurgarh",
  "Balarampur",
  "Barabanki",
  "Bareilly",
  "Bareli",
  "Barpeta Road",
  "Bassi Pathana",
  "Batote",
  "Bazpur",
  "Belarbahara",
  "Belargaon",
  "Bhadrachalam",
  "Bhagta Bhai Ka",
  "Bhavnagar",
  "Bhesan",
  "Bhongir",
  "Bhuntar",
  "Bichhiya",
  "Birbhum",
  "Bodinayakanur(Uzhavar Sandhai )",
  "Boraee",
  "Brahmpur",
  "Budalada",
  "Buland Shahr",
  "Chamba",
  "Chamkaur Sahib",
  "Chandigarh(Grain/Fruit)",
  "Charla",
  "Charra",
  "Chavakkad",
  "Chengalpet(Uzhavar Sandhai )",
  "Chengam(Uzhavar Sandhai )",
  "Chengannur",
  "Cheyyar(Uzhavar Sandhai )",
  "Chhachrauli",
  "Chhuria",
  "Chidambaram(Uzhavar Sandhai )",
  "Chikkamagalore",
  "Chinnalapatti(Uzhavar Sandhai )",
  "Chinnamanur(Uzhavar Sandhai )",
  "Chokkikulam(Uzhavar Sandhai )",
  "Coonoor(Uzhavar Sandhai )",
  "Cuddalore(Uzhavar Sandhai )",
  "Curchorem",
  "Dahod",
  "Deesa(Deesa Veg Yard)",
  "Dehgam",
  "Dehgam(Rekhiyal)",
  "Denkanikottai(Uzhavar Sandhai )",
  "Devakottai (Uzhavar Sandhai )",
  "Devarakonda",
  "Devaram(Uzhavar Sandhai )",
  "Devarkonda(Dindi)",
  "Devarkonda(Mallepalli)",
  "Devgadhbaria",
  "Dhamnod",
  "Dhanaura",
  "Dharapuram(Uzhavar Sandhai )",
  "Dharmapuri(Uzhavar Sandhai )",
  "Dhoraji",
  "Dhragradhra",
  "Dhrol",
  "Dindigul(Uzhavar Sandhai )",
  "Dindori",
  "Divai",
  "Dongargaon",
  "Dubbak",
  "Dudu",
  "Edapadi (Uzhavar Sandhai )",
  "Elampillai(Uzhavar Sandhai )",
  "Etah",
  "Ettumanoor",
  "Farukhabad",
  "Fazilka",
  "Gadarpur",
  "Gadarwada",
  "Gadwal(Lezza)",
  "Gajwel",
  "Ganaur",
  "Gandarvakottai(Uzhavar Sandhai )",
  "Garh Shankar",
  "GarhShankar (Kotfatuhi)",
  "Gattasilli",
  "Ghatal",
  "Ghiraur",
  "Gingee(Uzhavar Sandhai )",
  "Gobichettipalayam(Uzhavar Sandhai )",
  "Gogamba",
  "Gogamba(Similiya)",
  "Gohana",
  "Gonda",
  "Gondal(Veg.market Gondal)",
  "Gudalur(Uzhavar Sandhai )",
  "Gudiyatham(Uzhavar Sandhai )",
  "Guduvancheri(Uzhavar Sandhai )",
  "Gulabpura",
  "Gurgaon",
  "Haliyala",
  "Halvad",
  "Hansi",
  "Harappana Halli",
  "Hargaon (Laharpur)",
  "Haridwar Union",
  "Harippad",
  "Harur(Uzhavar Sandhai )",
  "Hasthampatti(Uzhavar Sandhai )",
  "Hosur(Uzhavar Sandhai )",
  "Husnabad",
  "Huzzurabad",
  "Indore",
  "Irinjalakkuda",
  "Jalagandapuram(Uzhavar Sandhai )",
  "Jalalabad",
  "Jalandhar City",
  "Jalandhar City(Jalandhar)",
  "Jalandhar City(Kartar Pur Dana mandi)",
  "Jalaun",
  "Jam Khambalia",
  "Jambusar",
  "Jambusar(Kaavi)",
  "Jameenrayapettai(Uzhavar Sandhai )",
  "Jangipur",
  "Jasdan",
  "Jetpur(Dist.Rajkot)",
  "Jeyankondam (Uzhavar Sandhai )",
  "Jhansi",
  "Jodhpur (F&V)",
  "Junagadh",
  "Kadakkal  VFPCK",
  "Kahithapattarai(Uzhavar Sandhai )",
  "Kairana",
  "Kalagategi",
  "Kalanjoor  VFPCK",
  "Kalavai",
  "Kalawad",
  "Kallachi",
  "Kallakurichi(Uzhavar Sandhai )",
  "Kalol",
  "Kambam(Uzhavar Sandhai )",
  "Kamlaganj",
  "Kancheepuram(Uzhavar Sandhai )",
  "Kandi",
  "Kandiyaperi(Uzhavar Sandhai )",
  "Kangayam(Uzhavar Sandhai )",
  "Kangra",
  "Kangra(Baijnath)",
  "Kangra(Jaisinghpur)",
  "Kangra(Nagrota Bagwan)",
  "Kanjirappally",
  "Karaikudi",
  "Karaikudi(Uzhavar Sandhai )",
  "Karambakkudi(Uzhavar Sandhai )",
  "Karanjia",
  "Karapa",
  "Kariyapatti(Uzhavar Sandhai )",
  "Karjat(Raigad)",
  "Karur(Uzhavar Sandhai )",
  "Kasdol",
  "Kasrawad",
  "Kathua",
  "Katpadi (Uzhavar Sandhai )",
  "Kaveripattinam(Uzhavar Sandhai )",
  "Kayamganj",
  "Keelpennathur(Uzhavar Sandhai )",
  "Khair",
  "Khambhat(Veg Yard Khambhat)",
  "Khanna",
  "Kharar",
  "Khargone",
  "Khateema",
  "Khatra",
  "Khetia",
  "Kicchha",
  "Kiratpur",
  "Koduvayoor",
  "Kollam",
  "Kollayil  VFPCK",
  "Kollengode",
  "Kondotty",
  "Koovapadi VFPCK",
  "Kopaganj",
  "Kosli",
  "Kottakkal",
  "Kottayam",
  "Kovilpatti(Uzhavar Sandhai )",
  "Krishnagiri(Uzhavar Sandhai )",
  "Kukshi",
  "Kulgam",
  "Kulithalai(Uzhavar Sandhai )",
  "Kullu",
  "Kullu(Chauri Bihal)",
  "Kullu(Patli Kuhal)",
  "Kumarapalayam(Uzhavar Sandhai )",
  "Kumbakonam (Uzhavar Sandhai )",
  "Kundrathur(Uzhavar Sandhai )",
  "Kurichi(Uzhavar Sandhai )",
  "Kuruppanthura",
  "Kustagi",
  "Ladwa",
  "Lakhimpur",
  "Lakshar",
  "Lalganj",
  "Lalgudi(Uzhavar Sandhai )",
  "Lingasugur",
  "Madathukulam",
  "Madhira",
  "Madhuranthagam(Uzhavar Sandhai )",
  "Maigalganj",
  "Mainpuri",
  "Mallial(Cheppial)",
  "Manachanallur(Uzhavar Sandhai )",
  "Manakodur",
  "Manapparai(Uzhavar Sandhai )",
  "Manawar",
  "Mandi(Mandi)",
  "Mandi(Takoli)",
  "Mandla",
  "Manglaur",
  "Mannargudi I(Uzhavar Sandhai )",
  "Mannargudi II(Uzhavar Sandhai )",
  "Maranelloor VFPCK",
  "Mayiladuthurai(Uzhavar Sandhai )",
  "Medavakkam(Uzhavar Sandhai )",
  "Melapalayam(Uzhavar Sandhai )",
  "Melur(Uzhavar Sandhai )",
  "Mettupalayam(Uzhavar Sandhai )",
  "Mettur(Uzhavar Sandhai )",
  "Mezhuveli  VFPCK",
  "Miryalaguda",
  "Mirzapur",
  "Modasa",
  "Modasa(Tintoi)",
  "Mohanur(Uzhavar Sandhai )",
  "Mohgaon",
  "Moothedam  VFPCK",
  "Morinda",
  "Morva Hafad",
  "Mukerian(Talwara)",
  "Mukkom",
  "Mullana",
  "Muriyad  VFPCK",
  "Musiri(Uzhavar Sandhai )",
  "Muthupettai(Uzhavar Sandhai )",
  "Myladi(Uzhavar Sandhai )",
  "NGO Colony(Uzhavar Sandhai )",
  "Naanpara",
  "Nagapattinam(Uzhavar Sandhai )",
  "Nagari",
  "Nalbari",
  "Namakkal(Uzhavar Sandhai )",
  "Nandyal",
  "Naravarikuppam(Uzhavar Sandhai )",
  "Narnaul",
  "Narwal Jammu (F&V)",
  "Narwana",
  "Natrampalli(Uzhavar Sandhai )",
  "Nautnava",
  "Needamangalam(Uzhavar Sandhai )",
  "Nelakondapally",
  "Neredcherla",
  "North Paravur",
  "Padappai(Uzhavar Sandhai )",
  "Pala",
  "Palacode(Uzhavar Sandhai )",
  "Palampur",
  "Palanganatham(Uzhavar Sandhai )",
  "Palani",
  "Palani(Uzhavar Sandhai )",
  "Palayamkottai(Uzhavar Sandhai )",
  "Palladam(Uzhavar Sandhai )",
  "Pallapatti (Uzhavar Sandhai )",
  "Pallavaram(Uzhavar Sandhai )",
  "Pampady",
  "Panchpedwa",
  "Panipat",
  "Panruti(Uzhavar Sandhai )",
  "Papanasam(Uzhavar Sandhai )",
  "Paramakudi(Uzhavar Sandhai )",
  "Paramathivelur(Uzhavar Sandhai )",
  "Parassala",
  "Parimpore",
  "Parlakhemundi",
  "Paruthipattu(Uzhavar Sandhai )",
  "Patiala",
  "Pattambi",
  "Patti",
  "Pattukottai(Uzhavar Sandhai )",
  "Peddapalli",
  "Pennagaram(Uzhavar Sandhai )",
  "Perambalur(Uzhavar Sandhai )",
  "Periyakulam(Uzhavar Sandhai )",
  "Periyar Nagar(Uzhavar Sandhai )",
  "Perumbavoor",
  "Perundurai(Uzhavar Sandhai )",
  "Pimpalgaon",
  "Pollachi(Uzhavar Sandhai )",
  "Polur(Uzhavar Sandhai )",
  "Pramadom VFPCK",
  "Pudukottai(Uzhavar Sandhai )",
  "Pudur",
  "Pulwama (F&V)",
  "Pune",
  "Pune(Moshi)",
  "RSPuram(Uzhavar Sandhai )",
  "Raibareilly",
  "Raipur",
  "Rajapalayam(Uzhavar Sandhai )",
  "Rajkot",
  "Rajnandgaon",
  "Rajouri (F&V)",
  "Rajpipla",
  "Ramanathapuram(Uzhavar Sandhai )",
  "Ramannapet",
  "Rampuraphul(Nabha Mandi)",
  "Rampurhat",
  "Rani",
  "Rania",
  "Ranipettai(Uzhavar Sandhai )",
  "Rasipuram(Uzhavar Sandhai )",
  "Ravulapelem",
  "Rewari",
  "Rishikesh",
  "Roorkee",
  "Safdarganj",
  "Sahiyapur",
  "Salon",
  "Sambhal",
  "Sampath Nagar(Uzhavar Sandhai )",
  "Sanawad",
  "Sankarankoil(Uzhavar Sandhai )",
  "Sankarapuram(Uzhavar Sandhai )",
  "Sankeshwar",
  "Sarangarh",
  "Sathiyamagalam(Uzhavar Sandhai )",
  "Sathur(Uzhavar Sandhai )",
  "Sattupalli",
  "Savarkundla",
  "Sendhwa",
  "Shahaswan",
  "Shamli",
  "Shopian",
  "Siddipet",
  "Sikanderabad",
  "Siliguri",
  "Singampunari(Uzhavar Sandhai )",
  "Singanallur(Uzhavar Sandhai )",
  "Sirkali(Uzhavar Sandhai )",
  "Sitapur",
  "Sivagangai (Uzhavar Sandhai )",
  "Sivakasi(Uzhavar Sandhai )",
  "Siyana",
  "Sooramangalam(Uzhavar Sandhai )",
  "Sriganganagar (F&V)",
  "Srivilliputhur(Uzhavar Sandhai )",
  "Sultanpur",
  "Sulur(Uzhavar Sandhai )",
  "Sundarapuram(Uzhavar Sandhai )",
  "Suratgarh",
  "Taliparamba",
  "Talwandi Sabo",
  "Tamarainagar(Uzhavar Sandhai )",
  "Tanakpur",
  "Tenali",
  "Tenkasi(Uzhavar Sandhai )",
  "Thalasserry",
  "Thalavadi(Uzhavar Sandhai )",
  "Thalavaipuram(Uzhavar Sandhai )",
  "Thalayolaparambu",
  "Thammampatti (Uzhavar Sandhai )",
  "Thanjavur(Uzhavar Sandhai )",
  "Thathakapatti(Uzhavar Sandhai )",
  "Theni(Uzhavar Sandhai )",
  "Thirukalukundram(Uzhavar Sandhai )",
  "Thirumangalam(Uzhavar Sandhai )",
  "Thirupathur",
  "Thondernad  VFPCK",
  "Thoothukudi",
  "Thrippunithura",
  "Thuraiyur",
  "Tindivanam",
  "Tiruchengode",
  "Tirupatthur(Uzhavar Sandhai )",
  "Tiruppur (North) (Uzhavar Sandhai )",
  "Tiruppur (South) (Uzhavar Sandhai )",
  "Tiruthuraipoondi(Uzhavar Sandhai )",
  "Tiruttani",
  "Tiruvallur(Uzhavar Sandhai )",
  "Tiruvannamalai(Uzhavar Sandhai )",
  "Tiruvarur(Uzhavar Sandhai )",
  "Tiruvellore",
  "Tuli",
  "Tuticorin(Uzhavar Sandhai )",
  "Udhagamandalam(Uzhavar Sandhai )",
  "Udumalpet",
  "Uklana",
  "Ulundurpettai",
  "Unava",
  "Usilampatty",
  "Uthiramerur",
  "Vadakkenchery",
  "Vadaseri",
  "Vadavalli(Uzhavar Sandhai )",
  "Valangaiman",
  "Valsad",
  "Vandavasi",
  "Vaniyamkulam  VFPCK",
  "Vaniyampadi(Uzhavar Sandhai )",
  "Vedasanthur(Uzhavar Sandhai )",
  "Velayuthampalayam(Uzhavar Sandhai )",
  "Vellore",
  "Vemulawada",
  "Veraval",
  "Vijaynagar",
  "Vikasnagar",
  "Vilaspur",
  "Viralimalai(Uzhavar Sandhai )",
  "Virudhunagar(Uzhavar Sandhai )",
  "Viruthachalam(Uzhavar Sandhai )",
  "Visavadar",
  "Vishalpur",
  "Viswan",
  "Voligonda",
  "Warangal",
  "Wazirganj",
  "Wyra",
  "Yalburga",
  "Zaloosa-Chararishrief (F&V)",
  "kalanwali",
];

export const grades = ["FAQ", "Large", "Local", "Medium", "Small"];

export const varieties = [
  "1001",
  "777 New Ind",
  "ADT 37",
  "American",
  "Amruthapani",
  "Ankola",
  "Annabesahai",
  "Apple",
  "Arhar (Whole)",
  "Arhar Dal(Tur)",
  "B P T",
  "Banana - Ripe",
  "Besrai",
  "Bhushavali(Pacha)",
  "Big",
  "Black",
  "Black Gram (Whole)",
  "Chakkarakeli(Red)",
  "Chakkarakeli(White)",
  "Coconut",
  "Common",
  "Cotton (Unginned)",
  "Darjeeling",
  "Delicious",
  "Deshi Red",
  "Deshi White",
  "Desi",
  "Desi(Bontha)",
  "Dhan",
  "Dollar Gram",
  "Dusheri",
  "French",
  "Green (Whole)",
  "Green Gram Dhall-I",
  "H-4(A) 27mm FIne",
  "Hybrid",
  "Hybrid Red (Cattle Feed)",
  "Hybrid/Local",
  "I.R. 36",
  "I.R. 64",
  "I.R.-64",
  "Karbhuja",
  "Karpura",
  "Kasmir/Shimla - II",
  "Kullu Royal Delicious",
  "Local",
  "Local (Whole)",
  "MTU-1010",
  "Masoor Gola",
  "Masur Dal",
  "Medium",
  "Nagpuri",
  "Narma BT Cotton",
  "Nendra Bale",
  "Orange",
  "Other",
  "Paddy",
  "Paddy Coarse",
  "Paddy Medium",
  "Paddy fine",
  "Paddy-Organic",
  "Palayamthodan",
  "Papaya",
  "Pomogranate",
  "Poovan",
  "RCH-2",
  "Rasakathai",
  "Red  Gold",
  "Red Banana",
  "Robusta",
  "Royal Delicious",
  "Safeda",
  "Samba Masuri",
  "Sarvati",
  "Shanker 6 (B) 30mm FIne",
  "Simla",
  "Small",
  "Sona",
  "Sona Mahsuri",
  "Swarna Masuri (New)",
  "TD-5",
  "Tur/Arhar-Organic",
  "Urda/Urd",
  "Water Melon",
  "White (SAFED)",
  "Without Ginned Cotton",
  "Yellow",
];